name: mobilefirst
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  transparent_image: ^2.0.1
  shimmer: ^2.0.0
  google_fonts: ^4.0.3
  cached_network_image: ^3.2.3
  date_format: ^2.0.7
  firebase_auth: ^4.2.8
  firebase_core: ^2.6.1
  flutter_bloc: ^8.1.2
  font_awesome_flutter: ^10.4.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_sign_in: ^6.0.0
  http: ^0.13.5
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.0.2
  scroll_to_index: ^3.0.1
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  freezed: ^2.2.1
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - .env
